### PR TITLE
add option to use aapt2

### PR DESCRIPTION
**Pull request by sh4dowb**
sometimes only checking for res/navigation isn't enough to use aapt2.

### CODE REVIEW

**Comment by NickstaDB** [comment]
Thanks @sh4dowb.

To clarify, is this to fix a problem where:

1. The `--use-aapt2` option was required, but the `res/navigation` directory was not present
2. The `res/navigation` directory was present, but the `--use-aapt2` option was not required

Are you also able to give an example of a public app where you have encountered this issue?

I'm not entirely opposed to adding a command-line option to force the use of `--use-aapt2` (or vice versa), but if the script can do a better job of detecting when `--use-aapt2` is required I'd prefer to implement that instead.

**Comment by sh4dowb** [comment]
> Thanks @sh4dowb.
> 
> To clarify, is this to fix a problem where:
> 
>     1. The `--use-aapt2` option was required, but the `res/navigation` directory was not present
> 
>     2. The `res/navigation` directory was present, but the `--use-aapt2` option was not required
> 
> 
> Are you also able to give an example of a public app where you have encountered this issue?
> 
> I'm not entirely opposed to adding a command-line option to force the use of `--use-aapt2` (or vice versa), but if the script can do a better job of detecting when `--use-aapt2` is required I'd prefer to implement that instead.

Hi, not the 2nd, only 1st.

```
W: /tmp/tmprjzbf2wn/*******/res/values/arrays.xml:1149: error: Error retrieving parent for item: No resource found that matches the given name 'currency'.
W: /tmp/tmprjzbf2wn/******/res/values/plurals.xml:7: error: Error retrieving parent for item: No resource found that matches the given name 'analytics.account_chooser'.
W: 
```

I'm getting errors like this from apktool
If I use aapt2 I don't get these errors, however, I noticed it **still happens with objection**. Maybe fix it for objection too, if there's the option for that, or just keep it the way it is?

**Comment by BenjaDiaz** [comment]
I have also found a case where res/navigation was not present, but the use of aapt2 was necessary for it to work. The error was:
```
W: /private/var/folders/w4/s5j65zls605cv0bzxdp0lg2w0000gp/T/tmplwhsykg8/XXX/res/values/drawables.xml:5: error: Error: String types not allowed (at 'abc_ab_share_pack_mtrl_alpha' with value '').
```

**Comment by NickstaDB** [comment]
It looks like an update to `apktool` changed the way some resource file elements are handled (see https://github.com/iBotPeaches/Apktool/issues/2462 and https://github.com/iBotPeaches/Apktool/commit/1422293b71b99806ef0afdf6ae9b8abdfb3087ac).

I've updated the script to enforce `--use-aapt2` if the installed `apktool` is newer than version 2.4.2, hopefully that will resolve the issues you've both experienced but let me know if not or if that breaks anything else. Cheers.

**Pull request closed without merging**
